//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Project3.SVC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HomeSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback pullSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaxSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback SizeSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback TypeSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookingOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateHomesOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback addClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback addHomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getClientIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRealtorIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getReservationsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::Project3.Properties.Settings.Default.Project3_SVC_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HomeSearchCompletedEventHandler HomeSearchCompleted;
        
        /// <remarks/>
        public event pullSetCompletedEventHandler pullSetCompleted;
        
        /// <remarks/>
        public event MaxSearchCompletedEventHandler MaxSearchCompleted;
        
        /// <remarks/>
        public event SizeSearchCompletedEventHandler SizeSearchCompleted;
        
        /// <remarks/>
        public event TypeSearchCompletedEventHandler TypeSearchCompleted;
        
        /// <remarks/>
        public event BookingCompletedEventHandler BookingCompleted;
        
        /// <remarks/>
        public event UpdateHomesCompletedEventHandler UpdateHomesCompleted;
        
        /// <remarks/>
        public event DeleteEntryCompletedEventHandler DeleteEntryCompleted;
        
        /// <remarks/>
        public event addClientCompletedEventHandler addClientCompleted;
        
        /// <remarks/>
        public event addHomeCompletedEventHandler addHomeCompleted;
        
        /// <remarks/>
        public event getClientIDCompletedEventHandler getClientIDCompleted;
        
        /// <remarks/>
        public event getRealtorIDCompletedEventHandler getRealtorIDCompleted;
        
        /// <remarks/>
        public event getReservationsCompletedEventHandler getReservationsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HomeSearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet HomeSearch(string city, string state) {
            object[] results = this.Invoke("HomeSearch", new object[] {
                        city,
                        state});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void HomeSearchAsync(string city, string state) {
            this.HomeSearchAsync(city, state, null);
        }
        
        /// <remarks/>
        public void HomeSearchAsync(string city, string state, object userState) {
            if ((this.HomeSearchOperationCompleted == null)) {
                this.HomeSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHomeSearchOperationCompleted);
            }
            this.InvokeAsync("HomeSearch", new object[] {
                        city,
                        state}, this.HomeSearchOperationCompleted, userState);
        }
        
        private void OnHomeSearchOperationCompleted(object arg) {
            if ((this.HomeSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HomeSearchCompleted(this, new HomeSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pullSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet pullSet() {
            object[] results = this.Invoke("pullSet", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void pullSetAsync() {
            this.pullSetAsync(null);
        }
        
        /// <remarks/>
        public void pullSetAsync(object userState) {
            if ((this.pullSetOperationCompleted == null)) {
                this.pullSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpullSetOperationCompleted);
            }
            this.InvokeAsync("pullSet", new object[0], this.pullSetOperationCompleted, userState);
        }
        
        private void OnpullSetOperationCompleted(object arg) {
            if ((this.pullSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pullSetCompleted(this, new pullSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MaxSearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet MaxSearch(string city, string state, double max) {
            object[] results = this.Invoke("MaxSearch", new object[] {
                        city,
                        state,
                        max});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void MaxSearchAsync(string city, string state, double max) {
            this.MaxSearchAsync(city, state, max, null);
        }
        
        /// <remarks/>
        public void MaxSearchAsync(string city, string state, double max, object userState) {
            if ((this.MaxSearchOperationCompleted == null)) {
                this.MaxSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaxSearchOperationCompleted);
            }
            this.InvokeAsync("MaxSearch", new object[] {
                        city,
                        state,
                        max}, this.MaxSearchOperationCompleted, userState);
        }
        
        private void OnMaxSearchOperationCompleted(object arg) {
            if ((this.MaxSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaxSearchCompleted(this, new MaxSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SizeSearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SizeSearch(string city, string state, int size) {
            object[] results = this.Invoke("SizeSearch", new object[] {
                        city,
                        state,
                        size});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SizeSearchAsync(string city, string state, int size) {
            this.SizeSearchAsync(city, state, size, null);
        }
        
        /// <remarks/>
        public void SizeSearchAsync(string city, string state, int size, object userState) {
            if ((this.SizeSearchOperationCompleted == null)) {
                this.SizeSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSizeSearchOperationCompleted);
            }
            this.InvokeAsync("SizeSearch", new object[] {
                        city,
                        state,
                        size}, this.SizeSearchOperationCompleted, userState);
        }
        
        private void OnSizeSearchOperationCompleted(object arg) {
            if ((this.SizeSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SizeSearchCompleted(this, new SizeSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TypeSearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TypeSearch(string city, string state, string type) {
            object[] results = this.Invoke("TypeSearch", new object[] {
                        city,
                        state,
                        type});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TypeSearchAsync(string city, string state, string type) {
            this.TypeSearchAsync(city, state, type, null);
        }
        
        /// <remarks/>
        public void TypeSearchAsync(string city, string state, string type, object userState) {
            if ((this.TypeSearchOperationCompleted == null)) {
                this.TypeSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTypeSearchOperationCompleted);
            }
            this.InvokeAsync("TypeSearch", new object[] {
                        city,
                        state,
                        type}, this.TypeSearchOperationCompleted, userState);
        }
        
        private void OnTypeSearchOperationCompleted(object arg) {
            if ((this.TypeSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TypeSearchCompleted(this, new TypeSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Booking", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Booking(int home, int client, int realtor) {
            object[] results = this.Invoke("Booking", new object[] {
                        home,
                        client,
                        realtor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BookingAsync(int home, int client, int realtor) {
            this.BookingAsync(home, client, realtor, null);
        }
        
        /// <remarks/>
        public void BookingAsync(int home, int client, int realtor, object userState) {
            if ((this.BookingOperationCompleted == null)) {
                this.BookingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookingOperationCompleted);
            }
            this.InvokeAsync("Booking", new object[] {
                        home,
                        client,
                        realtor}, this.BookingOperationCompleted, userState);
        }
        
        private void OnBookingOperationCompleted(object arg) {
            if ((this.BookingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookingCompleted(this, new BookingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateHomes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateHomes(string address, string city, string state, int price, int SF, string availability, int bedrooms, double bathrooms, string Type) {
            object[] results = this.Invoke("UpdateHomes", new object[] {
                        address,
                        city,
                        state,
                        price,
                        SF,
                        availability,
                        bedrooms,
                        bathrooms,
                        Type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateHomesAsync(string address, string city, string state, int price, int SF, string availability, int bedrooms, double bathrooms, string Type) {
            this.UpdateHomesAsync(address, city, state, price, SF, availability, bedrooms, bathrooms, Type, null);
        }
        
        /// <remarks/>
        public void UpdateHomesAsync(string address, string city, string state, int price, int SF, string availability, int bedrooms, double bathrooms, string Type, object userState) {
            if ((this.UpdateHomesOperationCompleted == null)) {
                this.UpdateHomesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateHomesOperationCompleted);
            }
            this.InvokeAsync("UpdateHomes", new object[] {
                        address,
                        city,
                        state,
                        price,
                        SF,
                        availability,
                        bedrooms,
                        bathrooms,
                        Type}, this.UpdateHomesOperationCompleted, userState);
        }
        
        private void OnUpdateHomesOperationCompleted(object arg) {
            if ((this.UpdateHomesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateHomesCompleted(this, new UpdateHomesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteEntry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteEntry(string ID) {
            this.Invoke("DeleteEntry", new object[] {
                        ID});
        }
        
        /// <remarks/>
        public void DeleteEntryAsync(string ID) {
            this.DeleteEntryAsync(ID, null);
        }
        
        /// <remarks/>
        public void DeleteEntryAsync(string ID, object userState) {
            if ((this.DeleteEntryOperationCompleted == null)) {
                this.DeleteEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteEntryOperationCompleted);
            }
            this.InvokeAsync("DeleteEntry", new object[] {
                        ID}, this.DeleteEntryOperationCompleted, userState);
        }
        
        private void OnDeleteEntryOperationCompleted(object arg) {
            if ((this.DeleteEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteEntryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string addClient(Client client) {
            object[] results = this.Invoke("addClient", new object[] {
                        client});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void addClientAsync(Client client) {
            this.addClientAsync(client, null);
        }
        
        /// <remarks/>
        public void addClientAsync(Client client, object userState) {
            if ((this.addClientOperationCompleted == null)) {
                this.addClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddClientOperationCompleted);
            }
            this.InvokeAsync("addClient", new object[] {
                        client}, this.addClientOperationCompleted, userState);
        }
        
        private void OnaddClientOperationCompleted(object arg) {
            if ((this.addClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addClientCompleted(this, new addClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addHome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string addHome(Home home) {
            object[] results = this.Invoke("addHome", new object[] {
                        home});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void addHomeAsync(Home home) {
            this.addHomeAsync(home, null);
        }
        
        /// <remarks/>
        public void addHomeAsync(Home home, object userState) {
            if ((this.addHomeOperationCompleted == null)) {
                this.addHomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddHomeOperationCompleted);
            }
            this.InvokeAsync("addHome", new object[] {
                        home}, this.addHomeOperationCompleted, userState);
        }
        
        private void OnaddHomeOperationCompleted(object arg) {
            if ((this.addHomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addHomeCompleted(this, new addHomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getClientID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getClientID() {
            object[] results = this.Invoke("getClientID", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getClientIDAsync() {
            this.getClientIDAsync(null);
        }
        
        /// <remarks/>
        public void getClientIDAsync(object userState) {
            if ((this.getClientIDOperationCompleted == null)) {
                this.getClientIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetClientIDOperationCompleted);
            }
            this.InvokeAsync("getClientID", new object[0], this.getClientIDOperationCompleted, userState);
        }
        
        private void OngetClientIDOperationCompleted(object arg) {
            if ((this.getClientIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getClientIDCompleted(this, new getClientIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getRealtorID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getRealtorID() {
            object[] results = this.Invoke("getRealtorID", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getRealtorIDAsync() {
            this.getRealtorIDAsync(null);
        }
        
        /// <remarks/>
        public void getRealtorIDAsync(object userState) {
            if ((this.getRealtorIDOperationCompleted == null)) {
                this.getRealtorIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRealtorIDOperationCompleted);
            }
            this.InvokeAsync("getRealtorID", new object[0], this.getRealtorIDOperationCompleted, userState);
        }
        
        private void OngetRealtorIDOperationCompleted(object arg) {
            if ((this.getRealtorIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRealtorIDCompleted(this, new getRealtorIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getReservations", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getReservations() {
            object[] results = this.Invoke("getReservations", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getReservationsAsync() {
            this.getReservationsAsync(null);
        }
        
        /// <remarks/>
        public void getReservationsAsync(object userState) {
            if ((this.getReservationsOperationCompleted == null)) {
                this.getReservationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReservationsOperationCompleted);
            }
            this.InvokeAsync("getReservations", new object[0], this.getReservationsOperationCompleted, userState);
        }
        
        private void OngetReservationsOperationCompleted(object arg) {
            if ((this.getReservationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReservationsCompleted(this, new getReservationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Client {
        
        private string firstNameField;
        
        private string lastNameField;
        
        /// <remarks/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Home {
        
        private string addressField;
        
        private string cityField;
        
        private string stateField;
        
        private int priceField;
        
        private int sfField;
        
        private string availabilityField;
        
        private int bedroomsField;
        
        private double bathroomsField;
        
        private string typeField;
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public int price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public int SF {
            get {
                return this.sfField;
            }
            set {
                this.sfField = value;
            }
        }
        
        /// <remarks/>
        public string availability {
            get {
                return this.availabilityField;
            }
            set {
                this.availabilityField = value;
            }
        }
        
        /// <remarks/>
        public int bedrooms {
            get {
                return this.bedroomsField;
            }
            set {
                this.bedroomsField = value;
            }
        }
        
        /// <remarks/>
        public double bathrooms {
            get {
                return this.bathroomsField;
            }
            set {
                this.bathroomsField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HomeSearchCompletedEventHandler(object sender, HomeSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HomeSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HomeSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void pullSetCompletedEventHandler(object sender, pullSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pullSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pullSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void MaxSearchCompletedEventHandler(object sender, MaxSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaxSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaxSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SizeSearchCompletedEventHandler(object sender, SizeSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SizeSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SizeSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void TypeSearchCompletedEventHandler(object sender, TypeSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TypeSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TypeSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void BookingCompletedEventHandler(object sender, BookingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BookingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BookingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateHomesCompletedEventHandler(object sender, UpdateHomesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateHomesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateHomesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteEntryCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addClientCompletedEventHandler(object sender, addClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addHomeCompletedEventHandler(object sender, addHomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addHomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addHomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getClientIDCompletedEventHandler(object sender, getClientIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getClientIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getClientIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getRealtorIDCompletedEventHandler(object sender, getRealtorIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRealtorIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRealtorIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getReservationsCompletedEventHandler(object sender, getReservationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReservationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReservationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591